---
swagger: "2.0"
info:
  description: "Todo REST API"
  version: "1.0.0"
  title: "Todo Swagger"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "niyantshah02@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:5000"
basePath: ""
tags:
- name: "todo"
  description: "Your daily Todo"
schemes:
- "http"
paths:
  /todo:
    get:
      tags:
      - "todo"
      summary: "Get all list"
      description: ""
      operationId: "index"
      consumes:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "Get all records."
        "500":
          description: "Something is wrong"
      x-swagger-router-controller: "Todo"
    post:
      tags:
      - "todo"
      summary: "Add a new todo to the store"
      description: ""
      operationId: "store"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Todo object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Todo"
      responses:
        "200":
          description: "Create Todo Successfully!"
        "404":
          description: "Content can not be empty!"
      x-swagger-router-controller: "Todo"
  /todo/{todoId}:
    get:
      tags:
      - "todo"
      summary: "Find todo by ID"
      description: "Returns a single todo"
      operationId: "show"
      produces:
      - "application/json"
      parameters:
      - name: "todoId"
        in: "path"
        description: "ID of todo to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Todo"
        "404":
          description: "Todo not found"
        "500":
          description: "Something is Wrong."
      x-swagger-router-controller: "Todo"
    put:
      tags:
      - "todo"
      summary: "Update an existing todo"
      description: ""
      operationId: "update"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "todoId"
        in: "path"
        description: "ID of todo to return"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Todo object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Todo"
      responses:
        "200":
          description: "Update successfully"
        "400":
          description: "Content can not be empty!"
        "404":
          description: "Todo not found"
        "500":
          description: "Something is Wrong."
      x-swagger-router-controller: "Todo"
    delete:
      tags:
      - "todo"
      summary: "Deletes a Todo"
      description: ""
      operationId: "delete"
      produces:
      - "application/json"
      parameters:
      - name: "todoId"
        in: "path"
        description: "Todo id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "Todo was deleted successfully!"
        "404":
          description: "Todo not found"
        "500":
          description: "Something is Wrong."
      x-swagger-router-controller: "Todo"
definitions:
  Todo:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      is_status:
        type: "boolean"
      created_at:
        type: "string"
      updated_at:
        type: "string"
    xml:
      name: "Todo"
    example:
      is_status: true
      updated_at: "updated_at"
      name: "name"
      created_at: "created_at"
      id: 0
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      result:
        type: "stirng"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
